version: '3.8'

services:
  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     TZ: Asia/Tokyo
  #   expose:
  #     - 5432
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres_volume:/var/lib/postgresql/data

  redis:
    image: redis:7
    expose:
      - 6379
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data

  push-serverless:
    build:
      context: ./
      dockerfile: ./apps/push-serverless/Dockerfile
    expose:
      - 8000
    ports:
      - '8081:80'
      - '1935:1935'
    env_file:
      - .env
    environment:
      SERVER_ENDPOINT: http://host.docker.internal:8080
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  # video_caddy:
  #   image: caddy:2
  #   ports:
  #     - '8082:80'
  #   volumes:
  #     - ./infra/video/Caddyfile:/etc/caddy/Caddyfile:ro
  #     - ./dockerdata/video-web/static:/srv/static:ro
  #   environment:
  #     VIDEO_DOMAIN: http://
#
  # video_agent:
  #   build:
  #     context: ./
  #     dockerfile: ./apps/video/Dockerfile
  #   container_name: video
  #   expose:
  #     - 8000
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./dockerdata/video-web/static:/home/node/static
  #   environment:
  #     SERVER_ENDPOINT: http://host.docker.internal:8080
  #   extra_hosts:
  #     - 'host.docker.internal:host-gateway'

volumes:
  postgres_volume:
  redis_volume:
