version: "3"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  redis:
    image: redis:7
    expose:
      - 6379
    ports:
      - 6379:6379

volumes:
  postgres_volume:
