version: '3'

services:
  srs:
    image: ossrs/srs:4
    restart: unless-stopped
    container_name: srs
    expose:
      - 8080
      - 1985
      - 1935
    ports:
      - 1935:1935
    volumes:
      - ./srs.conf:/usr/local/srs/conf/knzklive.conf:ro
      - ./push-web:/usr/local/srs/objs/nginx/html
    command: ./objs/srs -c conf/knzklive.conf

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./push-web/static:/srv/static:ro
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env

  #  srs:
  #    image: ossrs/srs:4
  #    restart: unless-stopped
  #    container_name: srs
  #    expose:
  #      - 8080
  #      - 1985
  #    ports:
  #      - 80:8080
  #      - 443:8081
  #      - 1935:1935
  #    volumes:
  #      - ./srs.conf:/usr/local/srs/conf/knzklive.conf:ro
  #      - /etc/letsencrypt/:/usr/local/srs/conf/ssl:ro
  #      - ./web:/usr/local/srs/objs/nginx/html
  #    command: ./objs/srs -c conf/knzklive.conf

  agent:
    image: ghcr.io/nzws/knzklive2-push:latest-arm64
    # build: .
    restart: unless-stopped
    container_name: push
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - ./push-web/static:/home/node/static

volumes:
  caddy_data:
    external: true
  caddy_config:
