name = "edge"
main = "src/index.ts"
compatibility_date = "2022-09-05"
routes = [
  # todo: env
	{ pattern = "edge.knzk.live", custom_domain = true }
]

[durable_objects]
bindings = [
  { name = "STREAMING_DURABLE_OBJECT", class_name = "StreamingDurableObject" },
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["StreamingDurableObject"]
