main = "src/index.ts"
compatibility_date = "2022-09-05"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["StreamingDurableObject"]

[env.production]
name = "knzklive-edge-production"
routes = [
	{ pattern = "edge.knzk.live", custom_domain = true }
]

[env.production.durable_objects]
bindings = [
  { name = "STREAMING_DURABLE_OBJECT", class_name = "StreamingDurableObject" },
]

[env.production.vars]
SERVER_ENDPOINT = "https://api.knzk.live"

[env.staging]
name = "knzklive-edge-staging"
routes = [
	{ pattern = "stg-edge.knzk.live", custom_domain = true }
]

[env.staging.durable_objects]
bindings = [
  { name = "STREAMING_DURABLE_OBJECT", class_name = "StreamingDurableObject" },
]


[env.staging.vars]
SERVER_ENDPOINT = "https://stg-api.knzk.live"

[env.development]
name = "knzklive-edge-development"

[env.development.durable_objects]
bindings = [
  { name = "STREAMING_DURABLE_OBJECT", class_name = "StreamingDurableObject" },
]

[env.development.vars]
SERVER_ENDPOINT = "http://localhost:8080"
