version: '3'

services:
  agent:
    # image: ghcr.io/nzws/knzklive-agent:latest
    build: .
    restart: unless-stopped
    expose:
      - 8080
    ports:
      - '8080:8080'
    networks:
      - inner-bridge
    environment:
      TZ: Asia/Tokyo
    volumes:
      - live_agent_shared:/usr/src/app/.mount
    healthcheck:
      test: ['CMD-SHELL', 'node ./dist/scripts/health.js']
      interval: 1s
      timeout: 5s
      retries: 30

  caddy:
    image: caddy:2
    restart: unless-stopped
    depends_on:
      agent:
        condition: service_healthy
    ports:
      - '80:80'
      - '443:443'
    networks:
      - inner-bridge
    volumes:
      - live_agent_shared:/etc/caddy
      - live_static:/srv
      - caddy_data:/data
      - caddy_config:/config

  srs:
    image: ossrs/srs:4
    restart: unless-stopped
    depends_on:
      agent:
        condition: service_healthy
    ports:
      - '1935:1935'
      - '1985:1985'
    expose:
      - 8080
    networks:
      - inner-bridge
    volumes:
      - live_agent_shared:/usr/local/srs
      - live_static:/usr/local/srs/objs/nginx/html
    command: ./objs/srs -c ./knzk.conf

volumes:
  caddy_data:
  caddy_config:
  live_agent_shared:
  live_static:

networks:
  inner-bridge:
    driver: bridge
