app = "knzklive-staging"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  # dockerfile = "../../apps/server/Dockerfile"
  image = "ghcr.io/nzws/knzklive2-server:staging"

[deploy]
release_command = "yarn workspace server prisma migrate deploy && exit 0"

[env]
  NODE_ENV = "production"
  SERVER_ENDPOINT = "https://stg-api.knzk.live"
  DEFAULT_FRONT_DOMAIN = "stg.knzk.live"
  EDGE_ENDPOINT = "wss://stg-edge.knzk.live"
  PUSH_DOMAIN = "stg-push.knzk.live"
  MASTODON_DOMAIN="don.nzws.me"
  REDIS_USE_IPV6 = "true"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
