version: '3'

services:
  srs:
    image: ossrs/srs:4
    restart: unless-stopped
    container_name: srs
    expose:
      - 8080
      - 1985
    ports:
      - 1935:1935
    volumes:
      - ./srs.conf:/usr/local/srs/conf/knzklive.conf:ro
      - ./live:/usr/local/srs/objs/nginx/html/live
    command: ./objs/srs -c conf/knzklive.conf

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./live:/srv/live
      - caddy_data:/data
      - caddy_config:/config

  agent:
    image: ghcr.io/nzws/knzklive2-push:latest
    # build: .
    restart: unless-stopped
    container_name: push
    expose:
      - 8000
    env_file:
      - .env

volumes:
  caddy_data:
    external: true
  caddy_config:
