# fly.toml app configuration file generated for knzklive2-push-prd on 2024-05-13T22:50:30+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'knzklive2-push-prd'
primary_region = 'nrt'

[build]
image = "ghcr.io/nzws/knzklive2-push-serverless:latest-amd64"

[processes]
app = "/knzk/entry.sh"

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

# (Experimental) RTMPS
[[services]]
internal_port = 1935
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']
[[services.ports]]
handlers = ["tls"]
port = 1936

# RTMP (IPv6 only)
[[services]]
internal_port = 1935
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']
[[services.ports]]
port = 1935

[[vm]]
size = 'performance-2x'
