name: Build push

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      tag:
        description: 'Docker tag (staging→staging, production→latest)'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - latest

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          file: ./apps/push/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/nzws/knzklive2-push:${{ inputs.tag }}-amd64
          cache-from: type=registry,ref=ghcr.io/nzws/knzklive2-push:${{ inputs.tag }}-amd64
          cache-to: type=inline
