name: Build images

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
      push: ${{ steps.filter.outputs.push }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            server:
              - 'apps/server/**'
            push:
              - 'apps/push/**'

  build-server:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.server == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          file: ./apps/server/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/nzws/knzklive2-server:${{ inputs.tag }}
          cache-from: type=registry,ref=ghcr.io/nzws/knzklive2-server:${{ inputs.tag }}
          cache-to: type=registry,ref=ghcr.io/nzws/knzklive2-server:${{ inputs.tag }},mode=max

  build-push:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.push == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: .
          file: ./apps/push/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/nzws/knzklive2-push:${{ inputs.tag }}
          cache-from: type=registry,ref=ghcr.io/nzws/knzklive2-push:${{ inputs.tag }}
          cache-to: type=registry,ref=ghcr.io/nzws/knzklive2-push:${{ inputs.tag }},mode=max
