name: Deploy Edge Network

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      CF_API_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --env ${{ inputs.environment }}
          workingDirectory: apps/edge
