name: Deploy Edge Network - production

on:
  push:
    branches:
      - production
    paths:
      - 'apps/edge/**'

jobs:
  deploy:
    uses: ./.github/workflows/_edge.yml
    with:
      environment: staging
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
