name: Release - staging/x64

on:
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/_lint.yml

  build-server:
    name: Build server
    needs: check
    uses: ./.github/workflows/_build_server.yml
    with:
      tag: staging
      environment: staging

  build-push:
    name: Build push
    needs: check
    uses: ./.github/workflows/_build_push.yml
    with:
      tag: staging
      environment: staging
