name: Release - production/x64

on:
  push:
    branches:
      - production

jobs:
  check:
    uses: ./.github/workflows/_lint.yml

  build-server:
    name: Build server
    needs: check
    uses: ./.github/workflows/_build_server.yml
    with:
      tag: latest
      environment: production

  build-push:
    name: Build push
    needs: check
    uses: ./.github/workflows/_build_push.yml
    with:
      tag: latest
      environment: production

  build-video:
    name: Build push
    needs: check
    uses: ./.github/workflows/_build_video.yml
    with:
      tag: latest
      environment: production
