name: Release - staging

on:
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/_lint.yml

  deploy:
    name: Deploy Edge Network
    needs: check
    uses: ./.github/workflows/_edge.yml
    with:
      environment: staging
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

  build:
    name: Build images
    needs: check
    uses: ./.github/workflows/_build.yml
    with:
      tag: staging
